# Generated by Django 4.1.4 on 2023-02-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domain', models.CharField(max_length=100)),
                ('Area', models.CharField(max_length=100)),
                ('Element', models.CharField(max_length=100)),
                ('Year', models.PositiveSmallIntegerField()),
                ('Temperatures', models.FloatField()),
                ('DewPoints', models.FloatField()),
                ('Humidity', models.PositiveSmallIntegerField()),
                ('WindSpeeds', models.FloatField()),
                ('Pressures', models.FloatField()),
                ('Percipitations', models.FloatField()),
                ('Date', models.CharField(max_length=100)),
                ('TypesOfCrops', models.CharField(max_length=100)),
                ('Unit', models.CharField(max_length=50)),
                ('Value', models.CharField(max_length=100)),
                ('Nutrients', models.CharField(max_length=100)),
                ('Soil', models.CharField(max_length=100)),
            ],
        ),
    ]
