# Generated by Django 4.1.4 on 2023-02-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvuploads',
            name='Area',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='csvuploads',
            name='Date',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='csvuploads',
            name='Domain',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='csvuploads',
            name='Element',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='csvuploads',
            name='Nutrients',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='csvuploads',
            name='Soil',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='csvuploads',
            name='TypesOfCrops',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='csvuploads',
            name='Value',
            field=models.CharField(max_length=300),
        ),
    ]
